apiVersion: v1
kind: Service
metadata:
  name: jobmgr
  namespace: manage
spec:
  type: NodePort
  selector:
    app: jobmgr
  ports:
  - name: jobmgrhttp
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32099