apiVersion: v1
kind: Service
metadata:
  name: appmgr
  namespace: manage
spec:
  type: NodePort
  selector:
    app: appmgr
  ports:
  - name: appmgrhttp
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32003