apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svrmgr
  namespace: manage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svrmgr
        track: stable
    spec:
      containers:
      - name: svrmgr
        image: harbor.paas.nl:5000/paas_platform/nl.paas.svrmgr:2.3
        imagePullPolicy: Always
        env:
        - name: PF_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SPRING_PROFILES_ACTIVE
          value: dev93
        - name: JVM_OPTS
          value: "-XX:MaxRAMPercentage=70.0 -XX:InitialRAMPercentage=70.0 -XX:MinRAMPercentage=70.0"
        - name: LOG_PATH
          value: "/nl/paas/jdklogs"
        ports:
        - containerPort: 8080
        resources:
           requests:
             cpu: 1
             memory: 3Gi
           limits:
             cpu: 1
             memory: 3Gi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: localpath
          mountPath: /nl/paas
        - name: log4j2
          mountPath: /usr/local/nldata/config
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: localpath
        hostPath:
          path: /dcoslog/nl/paas