apiVersion: v1
kind: Service
metadata:
  name: svrmgr
  namespace: manage
spec:
  type: NodePort
  selector:
    app: svrmgr
  ports:
  - name: svrmgrhttp
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32006